### ISSUE TITLE
Is the project scrapped?

### ISSUE THREAD

**Issue by The-Ladle** [combustion-engine/combustion#1]
It seems like no commits have been made since five years ago. Just wondering, also curious if the squirrel-sys repository is a rust compatible version of squirrel.

**Comment by novacrazy** [comment]
Yes, the project is scrapped. It was far too ambitious and my knowledge of game engine design was pretty terrible at the time.

From what I remember, I never got beyond setting up bindgen locally for squirrel-sys, nothing special at all. 

This crate is a few years more recent than mine but has the same concept: https://github.com/robbym/squirrel-sys

Shouldn't be too hard to fork that and update that version of squirrel.

**Comment by novacrazy** [comment]
Though unless you just really want to use Squirrel, there are vastly more mature and high-level bindings to Lua or even Julia.

**Comment by The-Ladle** [comment]
Ok
